### ISSUE TITLE
ラーメンのコメント

### ISSUE THREAD

**Issue by naga55** [tanacchi/our_ramen#4]
通堂
大学近くにも店舗があるため、琉大生には特に身近なラーメン店。
メインのラーメンは本格博多ラーメンをベースにしたとんこつラーメンと、沖縄の食材を生かした塩ラーメンとあり、それぞれとんこつラーメンを「おとこ味」塩ラーメンを「おんな味」と名付けている。

KEIJIRO
まぜ麺がメインのラーメン店であり、沖縄市ゴヤ十字路に店舗を構える。モチモチとした太麺にチャーシュー、メンマ、ネギなど豊富な具材がトッピングされており、下に溜まっているタレと絡めることで絶妙な旨さを引き出す。途中でラー油とお酢をかけることで味の雰囲気がガラリと変わる。一度訪れてみたいお店である。

大岩亭
大岩ラーメン検索すると二番目に「まずい」というワードが出てくるラーメンである。というのも、大岩ラーメンは日本一濃いラーメンとの異名があり、豚の頭、丸骨、豚足、昆布、生姜、椎茸、玉ねぎを煮込んだスープはほぼ固形で、レンゲが垂直するほどの粘り気を持つ。麺にまとわりつくそのスープが話題となり、観光地としても有名な店舗である。

大砲ラーメン
昭和28年創業の歴史あるラーメン店であり、福岡県久留米市を中心に12店舗を展開している。決して釜を空にすることなく守り継がれたこってり系の「呼び戻しスープ」が特徴である。麺は博多系より若干太めの細麺で、スープが絡みやすい。くどさや癖がなく、濃厚なのに飽きない味である。

**Comment by Fukuzawa3man** [comment]
コメント未記入

和 dining 清乃
http://www.konomise.com/chuki/seino/

ラーメン慶次郎
https://tabelog.com/tokyo/A1322/A132205/13108087/

麺屋一燈
http://www.menya-itto.com

哲麺
http://www.tetsumen.com

Homemade Ramen 麦苗
https://tabelog.com/tokyo/A1315/A131502/13194812/

千葉県
中華蕎麦 とみ田
http://www.tomita-cocoro.jp

静岡県
伊豆あまからや（カレーとラーメンの店）
http://izu-amakaraya.com

沖縄県
YumeWoKatareOkinawa
--Twitter
https://twitter.com/ywk_okinawa

**Comment by yoshiaki09** [comment]
あまからや
伊豆市にあるカレーとラーメンのお店。店長は農業と兼業のため、週末営業となるが、スパイス醤油ラーメン(850円)は、 『第1回ラーメン登竜門』で全く新しい味として1位を取り、 カレーではなく10数種類のスパイスを独自にブレンドし、スパイス醤油だれとし、滋味豊かなスープと合わさっている。ちょっと刺激的で不思議な楽しい味になっている

 麺屋一燈
濃厚な鶏白湯スープに5種類の魚介、甲殻類を混ぜ合わせ高濃度に炊き上げた他では絶対に真似の出来ないつけ麺である濃厚魚介つけ麺と、スープを取るガラを通常の3倍使用した（塩）芳醇香味そばがある

**Comment by Fukuzawa3man** [comment]
和 dining 清乃

こだわりの「角長醤油匠」を使ってあっさりと仕上げた醤油ラーメンや，油を使わず豚骨でコッテリと仕上げた身体に優しいラーメンは女性におすすめ

**Comment by yoshiaki09** [comment]
自分が担当するコメント
 哲麺
豚骨を６時間、鶏ガラは３時間、じっくり別々に煮だし、オリジナル「マー油」で仕上げているクリーミーな豚骨スープとオリジナルの低加水の極細麺を使用。麺のゆで方、味の濃さ、脂の量が調整可能で自分好みの一杯に
中華蕎麦 とみ田
清潔感があるこじんまりとしたつけ麺・中華蕎麦店。国産小麦のみを使用した自家製麺と濃厚な豚骨魚介つけ汁を味わえる。カウンター席のみ。

**Comment by yoshiaki09** [comment]
ヌードル ラボラトリー 金斗雲
打ち放しコンクリートのカジュアルな店内に、木製カウンター席と小上がり席を用意。自家製麺と豚骨スープの醤油、塩、味噌ラーメンを提供。

**Comment by Fukuzawa3man** [comment]
***佐賀県***
丸幸ラーメンセンター
http://www.marukoura-men.com/

420円で身も心も財布も大満足！安くて美味しいラーメンを提供する老舗のラーメン店．

いちげん
--食べログ
https://tabelog.com/saga/A4101/A410101/41000068/

こってりなのに優しい味わいの豚骨スープがうまい！


***長崎県***
らーめん砦
http://kaipaitan.com

ラーメン嫌いの店主が作る新しい味．名前からは想像つかないラーメンと味をお楽しみいただけます．

***宮崎県***
栄養軒
http://eiyouken.ocnk.net

創業から54年間，一切味を変えずとも愛され続けた老舗店．あっさりスープとコシの強い自家製面は宮崎ラーメンの原点ともいえる．


***熊本県***
火の国文龍
https://tabelog.com/kumamoto/A4301/A430101/43000770/

スープまで飲み干してしまうほどに旨い！熊本のラーメンといえばここ！

***大分県***
トラの夢
https://tabelog.com/oita/A4401/A440101/44003515/

隠れたラーメン大国大分！濃厚でコクのある豚骨スープと完全無添加の自家製面の美味しさはトラの夢ならではの味！

**Comment by Fukuzawa3man** [comment]
Homemade Ramen 麦苗
口に広がるのは計算し尽くされた旨味は，食べログのラーメン部門で全国３位と評価は高い！

**Comment by Fukuzawa3man** [comment]
中華蕎麦 とみ田
拘り抜いたスープと国産小麦を使用した自家製麺は抜群の相性！

**Comment by Fukuzawa3man** [comment]
YumeWoKatareOkinawa
"皆で作るお店"　「夢を語って，仲間を作って，楽しい毎日を過ごす」ことを理念としたちょっと変わったラーメン店．

**Comment by tanacchi** [comment]
おかげ様で良いプロダクトができました
ありがとうございました！
