### ISSUE TITLE
ラーメン

### ISSUE THREAD

**Issue by Fukuzawa3man** [tanacchi/our_ramen#8]
***和歌山県***
和 dining 清乃
http://www.konomise.com/chuki/seino/

***東京都***
ラーメン慶次郎
--食べろぐ
https://tabelog.com/tokyo/A1322/A132205/13108087/

麺屋一燈
http://www.menya-itto.com

哲麺
http://www.tetsumen.com

Homemade Ramen 麦苗
--食べログ
https://tabelog.com/tokyo/A1315/A131502/13194812/

***千葉県***
中華蕎麦 とみ田 
http://www.tomita-cocoro.jp

***静岡県***
伊豆あまからや（カレーとラーメンの店）
http://izu-amakaraya.com

***愛知県***
大岩亭
--食べログ
https://tabelog.com/aichi/A2305/A230503/23041084/
--日本一濃いラーメンまとめ
https://matome.naver.jp/odai/2146486768102662901

***福岡県***
大砲ラーメン（本店）
http://www.taiho.net

***沖縄県***
通堂
http://www.ryoji-family.co.jp/ryukyushinmen_tondo.html

麺やKEIJIRO（画像あり）
--食べろぐ
https://tabelog.com/okinawa/A4703/A470301/47013427/
--ひとさら
https://hitosara.com/tlog_47018851/

YumeWoKatareOkinawa
--Twitter
https://twitter.com/ywk_okinawa

**Comment by yoshiaki09** [comment]
鹿児島県
ヌードル ラボラトリー 金斗雲
https://tabelog.com/kagoshima/A4601/A460101/46008456/

**Comment by Fukuzawa3man** [comment]
***佐賀県***
丸幸ラーメンセンター
http://www.marukoura-men.com/

420円で身も心も財布も大満足！安くて美味しいラーメンを提供する老舗のラーメン店．

いちげん
--食べログ
https://tabelog.com/saga/A4101/A410101/41000068/

こってりなのに優しい味わいの豚骨スープがうまい！


***長崎県***
らーめん砦
http://kaipaitan.com

ラーメン嫌いの店主が作る新しい味．名前からは想像つかないラーメンと味をお楽しみいただけます．

***宮崎県***
栄養軒
http://eiyouken.ocnk.net

創業から54年間，一切味を変えずとも愛され続けた老舗店．あっさりスープとコシの強い自家製面は宮崎ラーメンの原点ともいえる．


***熊本県***
火の国文龍
https://tabelog.com/kumamoto/A4301/A430101/43000770/

スープまで飲み干してしまうほどに旨い！熊本のラーメンといえばここ！

***大分県***
トラの夢
https://tabelog.com/oita/A4401/A440101/44003515/

隠れたラーメン大国大分！濃厚でコクのある豚骨スープと完全無添加の自家製面の美味しさはトラの夢ならではの味！

**Comment by tanacchi** [comment]
みなさんお元気で〜〜
